name: Generate ASCII Artwork

on: push

jobs:
    build-job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        - name: List Repo Files
          run: ls -ltra

    test-job:
        runs-on: ubuntu-latest
        steps:       
        - name: Test File Exists
          run: grep -i "dragon" dragon.txt
          
    deploy-job:
        runs-on: ubuntu-latest
        steps: 
        - name: Read File
          run: cat dragon.txt

        