name: My First Workflow

on: push

jobs:
    first-job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Welcome Message
          run: echo "My first Github Actions job"

        - name: List and Read files
          run: |
            echo "Listing and Reading Files"
            ls -ltra
            cat README.md
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt